out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  entity: tz545
  project: EGFR
dataset:
  format: OGB-EGFR
  name: EGFR_compounds_lipinsky.csv
  dir: './datasets'
  task: graph
  task_type: regression
  transductive: False
  split: [0.7, 0.2, 0.1]
  split_mode: random
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
pretrained:
  dir: pretrained/pcqm4m-GPS+RWSE.deep
  reset_prediction_head: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
model:
  type: GPSModel
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 16
  n_heads: 8
  dim_hidden: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 256  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0002
  max_epoch: 150
  scheduler: linear_with_warmup
  num_warmup_epochs: 10